var mongoose = require('mongoose');

// over here i am creating a model for the product, i will refer to the product using
// a unique ID, but that is automatically generated by the Mongoose ORM
var product = mongoose.model('product', {
  name:{
    type: String,
    unique:true,
    required: true,
    minlength: 4,
    trim: true
  },
  inventory:{
    type: Number,
    required: true,

  },
  price:{
    type: Number,
    required:true,
    min: 1
  }
});

module.exports = {product};
