var mongoose = require('mongoose');
mongoose.plugin(schema => { schema.options.usePushEach = true });

var {cartItem} = require('./cartItem')


// over here i am creating a model for the product, i will refer to the product using
// a unique ID, but that is automatically generated by the Mongoose ORM
var user = mongoose.model('user', {
  googleId:{
    type: String,
  },
  cart: {
    type:[[]],
    default: []
  },
  subtotal:{
    type: Number,
    default: 0
  }

});

module.exports = {user};
